name: Fin Bot AI CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Change directory
        run: cd /fin-bot/fin-bot-ai/fin-bot-ai

      - name: Run
        run: pm2 restart fin-bot-ai
